name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # 코드 내려받기
      - name: Checkout
        uses: actions/checkout@v2

      # 프로젝트 빌드
      - name: Build project
        run: 
          npm run build
      
      # 빌드 폴더 캐싱
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}


      - name: echo test result
        run: echo 'Hello, GitHub Actions!'

      - name: echo test result
        run: echo steps.cypress_result.outputs